services:
  db:
    image: mysql:5.7
    container_name: jphacks_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --general-log=true --general-log-file=/var/log/mysql/general.log
    environment:
      MYSQL_DATABASE: jphacks
      MYSQL_USER: jphacks
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql:delegated
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 1s
      timeout: 5s
      retries: 20

  client:
    container_name: jphacks_client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
      args:
        target: dev
    volumes:
      - ./client:/app
    ports:
      - 3000

  web:
    container_name: jphacks_web
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
      args:
        target: dev
    volumes:
      - ./server:/app
    ports:
      - 4000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4000 || exit 1
      interval: 1s
      timeout: 5s
      retries: 20

  nginx:
    container_name: jphacks_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      SERVER_HOST: web
      CLIENT_HOST: client
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_started
      client:
        condition: service_started

volumes:
  db-data:
    name: jphacks-db-data
    external: true
